"""Add llm_model to rca_reports

Revision ID: 77ae7cd6e02f
Revises: 9088011e1773
Create Date: 2026-03-25 15:19:15.591621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ae7cd6e02f'
down_revision: Union[str, None] = '9088011e1773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rca_reports', sa.Column('llm_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rca_reports', 'llm_model')
    # ### end Alembic commands ###
