"""Add sanitized_trace to incidents

Revision ID: 9088011e1773
Revises: 0a865dfc32fe
Create Date: 2026-03-25 15:14:39.820228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9088011e1773'
down_revision: Union[str, None] = '0a865dfc32fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('sanitized_trace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'sanitized_trace')
    # ### end Alembic commands ###
